app/main/__init__.py
#encoding:utf8
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
#encoding:utf8
from flask import render_template, request, g, abort, redirect, url_for, flash
from ..main import main
from flask_login import login_user, current_user
from ..models import db, Answer, Like_answer, Question, Comment_answer, User, Attention_question
import collections
import sqlalchemy
from flask_login import login_required



@main.route('/')
@main.route('/index')
def index():
    ''' 主页
        调用Answer的静态方法，获取赞数最多的答案
    '''
    answers = Answer.get_popular_answer()
    return render_template('main/index.html', answers = answers)


@main.route('/question/<question_id>')
def question(question_id):
    '''问题视图
       显示某问题的详细信息，包括关注数、提问者、提问时间、它的答案、答案的评论
    '''
    #通过question的id查询出question
    question = Question.query.filter_by(id=int(question_id)).first()
    #如果问题不存在，返回404页面
    if not question:
        abort(404)
    #获取问题的所有答案，并按赞序排序
    answers = question.answer_sort_by_like()
    return render_template('main/question.html', question = question, answers=answers)



@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    '''提问视图
    提供一个输入问题的表单
    '''
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        new_question = Question(title=title, description=description, user_id=current_user.id)
        db.session.add(new_question)

        db.session.commit()
        return redirect(url_for('main.question_list',ask_or_atten='ask',user_id=current_user.id))
    return render_template('main/ask.html')

@main.route('/search', methods=['GET', 'POST'])
def search():
    '''搜索视图，可在数据库中搜索问题的标题、答案的内容、用户的名字，使用%str%正则表达式'''
    res_question,res_answer,res_user = ([],[],[])
    if request.method == "POST":
        keyword = request.form['keyword']
        res_question = Question.query.filter(Question.title.like('%'+str(keyword)+'%')).all()
        res_answer = Answer.query.filter(Answer.content.like('%'+str(keyword)+'%')).all()
        res_user = User.query.filter(User.name.like('%'+str(keyword)+'%')).all()
    return render_template('main/search.html',res_question = res_question,
                                              res_answer = res_answer,
                                              res_user = res_user)



@main.route('/dynamic')
@login_required
def dynamic():
    '''用户的动态，显示用户的关注者最新（从此用户上次登录的时间点开始到现在）回答过的、赞过的答案
    '''
    pass

@main.route('/question_list/<ask_or_atten>/<user_id>')
def question_list(ask_or_atten,user_id):
    '''显示用户提问的或者关注的问题的列表'''
    user = User.query.get(int(user_id))
    if ask_or_atten == 'ask':
        res = Question.query.filter_by(user_id=int(user_id)) 
    if ask_or_atten == 'atten':
        res = user.counter_question_attention()[0]
    return render_template('main/question_list.html', res=res, user=user)

@main.route('/submit_comment/<answer_id>/<question_id>', methods=['POST'])
@login_required
def submit_comment(answer_id, question_id):
    '''提交答案的评论的视图函数，只能用POST请求访问，作为一个跳板，不论评论成功还是失败
    都重定向到question视图，返回之前的问题详情页面'''
    comment_content = request.form.get('comment_content',None)
    if comment_content is not None:
        new_comment = Comment_answer(user_id=current_user.id,answer_id=answer_id,
                                     content=request.form['comment_content'])
        answer = Answer.query.get(answer_id)
        answer.comment_counter = answer.comment_counter + 1
        try:
            db.session.add(new_comment)
            db.session.add(answer)
            db.session.commit()
            flash("评论成功！")
        except:
            flash("数据库原因，评论失败！")

        return redirect(url_for('main.question',question_id=question_id))

@main.route('/submit_answer/<question_id>', methods=['POST'])
def submit_answer(question_id):
    '''提交问题的答案的视图函数,只能用POST请求访问，作为一个跳板，不论回答成功还是失败
    都重定向到question视图，返回之前的问题详情页面'''
    answer_content = request.form.get('answer_content',None)
    if answer_content is not None:
        new_answer = Answer(content=answer_content,user_id=current_user.id,
                            question_id=question_id)
        try:
            db.session.add(new_answer)
            db.session.commit()
            flash("评论成功！")
        except:
            flash("数据库原因，评论失败！")
    return redirect(url_for('main.question',question_id=question_id))

@main.route('/attention_question/<question_id>')
@login_required
def attention_question(question_id):
    '''传入question_id，查询登录的用户是否关注了此问题，若关注，则取消，若未，则关注'''
    _attention_question = Attention_question(user_id=current_user.id,question_id=question_id)
    db.session.add(_attention_question)
    try:
        db.session.commit()
        flash('关注成功！')
    except Exception as e:
        flash('关注失败（%s）' % e)
    if Question.update_attention_counter(question_id,'plus'):
        flash('更新此问题关注的总数成功！')
    else:
        flash('更新此问题关注的总数失败！')
    return redirect(request.referrer)   

@main.route('/cancel_attention_question/<question_id>')
@login_required
def cancel_attention_question(question_id):
    '''传入question_id，查询登录的用户是否关注了此问题，若关注，则取消，若未，则关注'''
    _attention_question = Attention_question.query.filter_by(
                    user_id=current_user.id,question_id=question_id).first()
    db.session.delete(_attention_question)
    try:
        db.session.commit()
        flash('取消关注成功！')

    except Exception as e:
        flash('取消关注失败（%s）' % e)
    if Question.update_attention_counter(question_id,'less'):
        flash('更新此问题关注的总数成功！')
    else:
        flash('更新此问题关注的总数失败！')

    return redirect(request.referrer)     

@main.route('/like_answer/<answer_id>')
@login_required
def like_answer(answer_id):
    '''传入answer_id，加上当前用户，在数据表Like_answer中插入一行,
    并在answer的like_counter中相应位置+1,从而实现点赞功能'''
    _like_answer = Like_answer(user_id=current_user.id,answer_id=int(answer_id))
    db.session.add(_like_answer)
    try:
        db.session.commit()
        flash('点赞成功！')
    except Exception as e:
        flash('点赞失败（%s）'%e)
    if Answer.update_like_counter(answer_id=answer_id,plus_or_less='plus'):
        flash('更新答案的总赞数成功！')
    else:
        flash('更新答案的总赞数失败！')
    if User.update_like_counter(answer_id=answer_id,plus_or_less='plus'):
        flash('更新用户的总赞数成功！')
    else:
        flash('更新用户的总赞数失败！')
    return redirect(request.referrer)

@main.route('/cancel_like_answer/<answer_id>')
@login_required
def cancel_like_answer(answer_id):
    '''传入answer_id，加上当前用户，在数据表Like_answer中插入一行,
    并在answer的like_counter中相应位置+1,从而实现点赞功能'''
    _like_answer = Like_answer.query.filter_by(user_id=current_user.id,answer_id=answer_id).first()
    db.session.delete(_like_answer)
    try:
        db.session.commit()
        flash('取消赞成功！')
    except Exception as e:
        flash('取消赞失败（%s）'%e)
    if Answer.update_like_counter(answer_id=answer_id,plus_or_less='less'):
        flash('更新赞数成功！')
    else:
        flash('更新赞数失败！')
    if User.update_like_counter(answer_id=answer_id,plus_or_less='less'):
        flash('更新用户的总赞数成功！')
    else:
        flash('更新用户的总赞数失败！')
    return redirect(request.referrer)

@main.route('/like_list/<like_or_bylike>/<user_id>')
def like_list(like_or_bylike,user_id):
    '''显示用户赞或者被赞的条目，返回给前端的是Like_answer的查询结果的列表'''
    user = User.query.get(user_id)
    if like_or_bylike == 'like':    
        res = user.counter_like_answer()
    if like_or_bylike == 'bylike':
        res = user.counter_bylike()
    return render_template('main/like_list.html',res=res,user=user,like_or_bylike=like_or_bylike)

@main.route('/answers_list/<user_id>')
def answers_list(user_id):
    user = User.query.get(user_id)
    answers = user.answer_asked()
    return render_template('main/answers_list.html',res=answers,user=user)













app/templates/main/answers_list.html
{% extends './base.html' %}
	{% block content %}
	<div class="span9">
				
				<h1 class="page-title">
					<i class="icon-pushpin"></i>
					{{ user.name }}的答案					
				</h1>
			</div>

	<div class="span9">

<ul>
				{% for answer in res[0] %}
			
					<li>
					<a href='{{url_for('auth.change_account',user_id=answer.user.id)}}'>{{answer.user.name}}
					</a>
					于{{answer.add_time}}回答了
					<a href='{{url_for('auth.change_account',user_id=answer.question.user.id)}}'>{{answer.question.user.name}}
					</a>
					的答案（<a href="{{url_for('main.question',question_id=answer.question.id)}}">我也要答</a>）：<br><p class="indentation">{{answer.content}}</p>
				</li>
				{% endfor %}
				</ul>
	</div>
	{% endblock %}

app/templates/main/ask.html
{% extends './base.html' %}
	{% block content %}
	<div class="span9">
	
	<h1 class="page-title">
		<i class="icon-pushpin"></i>
		问题编辑					
	</h1>
	</div>
	<div class="span9">
		<form action="/ask" method="post">	
			<div>
			<label><strong>问题标题</strong></label>
			<input style="width:90%" name="title" />
			<label><strong>问题描述</strong></label>
			<textarea style="width:90%" class="form-control" rows="10" name="description"></textarea>
			<br>
			
			</div>
			<div style="text-align:center"><input type="submit" value="提交" /></div>
			

		</form>

	</div>
	{% endblock %}

app/templates/main/index.html
 {% extends "./base.html" %}
{% block content %}
			
<div class="span9">
				
				<h1 class="page-title">
					<i class="icon-th-large"></i>
					热门					
				</h1>
			{% if answers == [] %}
				<h2>数据库出错！</h2>
			{% else %}
				{% for answer in answers %}

				<div class="row">
					
					<div class="span9">
				
						<div class="widget">
									
							<div class="widget-content">
								
								<h3><a href='{{ url_for('main.question',question_id=answer.question.id) }}'>{{ answer.question.title}}</a></h3>
								<p><font size="2" face="arial" color="black"><a href="{{url_for('auth.change_account',user_id=answer.user.id)}}">{{answer.user.name}}</a>发表于{{ answer.question.add_time }}</font></p>

								<div class="box">
								<p class="indentation">{{ answer.content }}</p>

								</div>
								<p align="right">
							{% if current_user.is_authenticated %}
								{% if current_user.judge_attention_question(answer.question.id) %}
								<a class="btn btn-default" href='{{url_for('main.cancel_attention_question',question_id=answer.question.id)}}' role="button">取消关注（{{ answer.question.attention_counter }}）</a>
								{% else %}
								<a class="btn btn-default" href='{{url_for('main.attention_question',question_id=answer.question.id)}}' role="button">关注（{{ answer.question.attention_counter }}）</a>
								{% endif %}
							{% else %}
								<a class="btn btn-default" href='{{url_for('main.attention_question',question_id=answer.question.id)}}' role="button">关注（{{ answer.question.attention_counter }}）</a>
							{% endif %}

								<a data-toggle="collapse" data-parent="#accordion" 
				  			href="#collapse{{answer.id}}" class="btn btn-default" role="button">评论（{{ answer.comment_counter }}）</a>
				  			{% if current_user.is_authenticated %}
				  				{% if current_user.judge_like_answer(answer.id) %}
								<a class="btn btn-default" href='{{url_for('main.cancel_like_answer',answer_id=answer.id)}}' role="button">取消赞（{{ answer.like_counter }}）</a>
								{% else %}
								<a class="btn btn-default" href='{{url_for('main.like_answer',answer_id=answer.id)}}' role="button">赞（{{ answer.like_counter }}）</a>
								{% endif %}
							{% else %}
								<a class="btn btn-default" href='{{url_for('main.like_answer',answer_id=answer_id)}}' role="button">赞（{{ answer.like_counter }}）</a>
							{% endif %}
								</p>
								<div id="collapse{{answer.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<div>
											<form method="post" action="{{url_for('main.submit_comment',answer_id=answer.id,question_id=answer.question.id)}}">
												<input style="width:100%;height:30px" name="comment_content" type="text" placeholder="写下您的评论"><br>
												<input style="width:10%;height:30px"  class="btn btn-info" type="submit" name="" value="提交">
											</form>

										</div>
									</div>
								</div>


								
							</div> <!-- /widget-content -->
							
						</div> <!-- /widget -->
						
					</div> <!-- /span9 -->

					
				</div> <!-- /row -->

				{% endfor %}
			{% endif %}		
					
	
				
			
{% endblock %}


{% block script %}

 
{% endblock %}

app/templates/main/like_list.html
{% extends "./base.html" %}
	{% block link %}
	    <link href="../../static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../static/css/bootstrap-responsive.min.css" rel="stylesheet" />
    
    
    <link href="../../static/css/font-awesome.css" rel="stylesheet" />
    
    <link href="../../static/css/adminia.css" rel="stylesheet" /> 
    <link href="../../static/css/adminia-responsive.css" rel="stylesheet" /> 
    
    
    <link href="../../static/css/pages/plans.css" rel="stylesheet" /> 
	{% endblock %}
	{% block content %}
			<div class="span9">
				
				<h1 class="page-title">
					<i class="icon-pushpin"></i>
					{{ user.name }}{% if like_or_bylike=='like' %}的赞{% else %}获得的赞{% endif %}					
				</h1>
				
			</div>
			<div class="span9">
<ul>
				{% for like_answer in res[0] %}
			
					<li>
					<a href='{{url_for('auth.change_account',user_id=like_answer.user.id)}}'>{{like_answer.user.name}}
					</a>
					于{{like_answer.like_time}}赞了
					<a href='{{url_for('auth.change_account',user_id=like_answer.answer.user.id)}}'>{{like_answer.answer.user.name}}
					</a>
					的答案（<a href="{{url_for('main.question',question_id=like_answer.answer.id)}}">我也要答</a>）：<br><p class="indentation">{{like_answer.answer.content}}</p>
				</li>
				{% endfor %}
				</ul>
			</div>
	{% endblock %}
	{% block script %}
	<script src="../../static/js/jquery-1.7.2.min.js"></script>


	<script src="../../static/js/bootstrap.js"></script>
	{% endblock %}
	{% block img %}
	<img src="../../static/img/headshot.png" alt="" class="thumbnail" />
	{% endblock %}

app/templates/main/question.html
{% extends "./base.html" %}
{% block bigcontent %}

<div>		
<div style="color:#ABB2B9;text-align: center;">
		<div>
		<h3>
		{{ question.title }}					
	</h3>

	</div>

	<div class="box">
		<h3>
		<strong>{{ question.title }}</strong> 			
	</h3>
		<h4>{{ question.description }}</h4>

	</div>

	{% if current_user.judge_attention_question(question.id) %}
	<a class="btn btn-default" href='{{url_for('main.cancel_attention_question',question_id=question.id)}}' role="button">取消关注（{{ question.attention_counter }}）</a>
	{% else %}
	<a class="btn btn-default" href='{{url_for('main.attention_question',question_id=question.id)}}' role="button">关注（{{ question.attention_counter }}）</a>
	{% endif %}

	
</div>



<div style="width:70%;margin-left:auto;margin-right:auto;">
		<div class="span9" style="margin: 0 auto">
		<form method="post" action="/submit_answer/{{question.id}}">
			<textarea style="width:100%;height:90px" name="answer_content" type="text" placeholder="写下您的答案"></textarea><br>

			<input style="width:10%;height:30px"  class="btn btn-info" type="submit" name="" value="提交">

		</form>		
		</div>
	{% for answer in answers %}
		<div class="span9" style="margin: 0 auto">
		  <div class="widget-content">
		  <a href="{{ url_for("auth.change_account",user_id=answer.user.id) }}">{{ answer.user.name }}</a>发表于{{ answer.add_time }}<br>
		  <p class="indentation">{{ answer.content }}	</p>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion" 
				  			href="#collapse{{answer.id}}">评论↓（{{ answer.comment_counter }}）
						</a>
						{% if current_user.judge_like_answer(answer.id) %}
						<a href="{{url_for('main.cancel_like_answer',answer_id=answer.id)}}">取消赞（{{ answer.like_counter }}）</a>
						
						{% else %}
						<a href="{{url_for('main.like_answer',answer_id=answer.id)}}">赞（{{ answer.like_counter }}）</a>
						{% endif %}
					</h4>
				</div>
			<div id="collapse{{answer.id}}" class="panel-collapse collapse">
				<div class="panel-body">
				<div>

					<form method="post" action="/submit_comment/{{ answer.id }}/{{question.id}}">
						<input style="width:85%;height:30px" name="comment_content" type="text" placeholder="写下您的评论">

						<input style="width:10%;height:30px"  class="btn btn-info" type="submit" name="" value="提交">
					</form>
				</div>
				{% if answer.comment_counter == 0 %}
				<p>此答案暂时还没有评论，快来评论吧</p>
				{% else %}
					{% for comment in answer.get_comment_answer()[0] %}
					<p class="indentation">{{ comment.content }}</p>
					<p style="text-align: right;"><a href="{{url_for('auth.change_account',user_id=comment.user_id)}}">{{comment.user.name}}</a>（发表于{{comment.add_time}}）</p>
					{% endfor %}
				{% endif %}
				</div>
			</div>
	
		  </div>
		</div>

</div>

	{% endfor %}



</div>

{% endblock %}
{% block foot %}

{% endblock %}
{% block img %}
{% endblock %}

app/templates/main/question_list.html
{% extends "./base.html" %}
	{% block link %}
	    <link href="../../static/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../static/css/bootstrap-responsive.min.css" rel="stylesheet" />
    
    
    <link href="../../static/css/font-awesome.css" rel="stylesheet" />
    
    <link href="../../static/css/adminia.css" rel="stylesheet" /> 
    <link href="../../static/css/adminia-responsive.css" rel="stylesheet" /> 
    
    
    <link href="../../static/css/pages/plans.css" rel="stylesheet" /> 
	{% endblock %}
	{% block content %}
			<div class="span9">
				
				<h1 class="page-title">
					<i class="icon-pushpin"></i>
					{{ user.name }}的问题列表					
				</h1>
			</div>
			<div class="span9">
			<ul>
				{% for question in res %}
				<li><a href="{{ url_for('main.question',question_id=question.id) }}"><h2>{{ question.title }}</h2></a></li>
				{% endfor %}
			</ul>
			</div>
	{% endblock %}
	{% block script %}
	<script src="../../static/js/jquery-1.7.2.min.js"></script>


	<script src="../../static/js/bootstrap.js"></script>
	{% endblock %}
	{% block img %}
	<img src="../../static/img/headshot.png" alt="" class="thumbnail" />
	{% endblock %}

app/templates/main/search.html
{% extends './base.html' %}
	{% block content %}
			<div class="span9">
				
				<h1 class="page-title">
					<i class="icon-pushpin"></i>
					搜索					
				</h1>
				
				<div class="widget">
														
					<div class="widget-content">
						<form method="post" action="/search">
						<div class="input-group col-md-3" style="text-align:center">  
				      		<input name="keyword" type="text" class="form-control" placeholder="问题/答案/用户名" / >  
				      		<br>
				            <span class="input-group-btn">  
				               <button class="btn btn-info btn-search">查找</button>  
				            </span>  
 						</div> 
 						</form>
								
					</div> <!-- /widget-content -->
					
				</div> <!-- /widget -->
				
				
				
			</div> <!-- /span9 -->
			<div class="span9">
			{% if res_question != [] %}
			<h1 class="page-title">
					<i class="icon-pushpin"></i>
					搜索结果（问题）					
				</h1>
			{% endif %}
			<ul>
							{% for question in res_question %}
								<li><a href="{{ url_for('main.question',question_id=question.id) }}">{{ question.title }}</a></li>
							{% endfor %}
			</ul>
			{% if res_answer != [] %}
			<h1 class="page-title">
					<i class="icon-pushpin"></i>
					搜索结果（答案）					
				</h1>
			{% endif %}
			<ul>
							{% for answer in res_answer %}
								<li><a href="{{ url_for('main.question',question_id=answer.question_id) }}">{{ answer.content }}</a></li>
							{% endfor %}
						</ul>
			{% if res_user != [] %}
			<h1 class="page-title">
					<i class="icon-pushpin"></i>
					搜索结果（用户名）					
				</h1>
			{% endif %}
			<ul>
							{% for user in res_user %}
								<li><a href="{{ url_for('auth.change_account',user_id=user.id) }}">{{ user.username }}</a></li>
							{% endfor %}
						</ul>
			</div>
	{% endblock %}

app/templates/main/write_text.html
{% extends './base.html' %}
	{% block content %}
	write_text
	{% endblock %}